### ISSUE TITLE
A raycast error is printing to the log when attempting to use the plugin brush in the viewport.

### ISSUE THREAD

**Issue by spalose** [IcterusGames/SimpleGrassTextured#1]
After installing the plugin, I am getting spammed with raycast and physics process errors when attempting to use the plugin's brush.

Godot 4 beta 17

![image](https://user-images.githubusercontent.com/5170787/216250708-c9618f52-14bd-4902-ac11-a2bb800f9c76.png)

**Comment by IcterusGames** [comment]
Fixed in version 1.0.4, this happened because the physics are in a separate thread (project settings->physics->3D->run_on_separate_thread)
