### ISSUE TITLE
Unshaded Texture Glitch

### ISSUE THREAD

**Issue by FeralBytes** [IcterusGames/SimpleGrassTextured#5]
When grass is un-shaded it seems to glitch at certain times and at certain distances. I have attached a video to better demonstrate the issue. I think it is related to the lights in the scene, but turning off all of the lights still results in weird glitches. If you have any ideas what we could do to avoid this issue that occurs at the transition between light sources, I would appreciate your insights. Thank you for this awesome addon.

https://github.com/IcterusGames/SimpleGrassTextured/assets/7874274/ef060dbc-a2f4-49c4-9083-3b3280e29c32

**Comment by FeralBytes** [comment]
Just an update on this issue so long as we have plenty of lights even in the transition areas it seems to prevent this issue. Basically no place can be dark as in no light, or else the un-shaded issue shows it self in the dark spots.

**Comment by IcterusGames** [comment]
Fixed in version 2.0.2

**Comment by FeralBytes** [comment]
After some testing we can confirm that 2.0.2 does indeed fix the un-shaded issue. Thank you.
