### ISSUE TITLE
Unshaded no longer accepts Albedo Color

### ISSUE THREAD

**Issue by FeralBytes** [IcterusGames/SimpleGrassTextured#6]
I could be wrong but Un-shaded should still accept the Albedo color right? in 2.0.2 Un-shaded will allow you to apply an Albedo Color but also immediately reverts the color when the scene is next reloaded. In the shader parameters Un-shaded causes it to pass white as the Albedo.

**Comment by IcterusGames** [comment]
Yes, you are right, unshaded mode should accept color albedo, fixed on version 2.0.3

**Comment by FeralBytes** [comment]
Thank you again. That was a very fast fix! We tested and 2.0.3 fixes the albedo on a un-shaded texture even in low to no light situations.
