### ISSUE TITLE
Shader Jitter At Certain Ranges

### ISSUE THREAD

**Issue by FeralBytes** [IcterusGames/SimpleGrassTextured#7]
So we encountered an interesting issue. The shader seems to twitch at certain ranges away from the world center. I tried to play around with the shader to isolate the issue but unfortunately I only either broke it or had no effect on the jitter. The jitter is not a Frames Per Second issue as documented in the attached videos. We also thought perhaps it was the sft_wind_pattern.png but trying a few different image versions of your image (High and Low Contrast Versions) did not resolve the issue. Can you please give us some insight into what may be causing the issue?
Please let me know if you need more details.

https://github.com/IcterusGames/SimpleGrassTextured/assets/7874274/d203ecac-6d73-47d9-9d6a-8f26f32cd3b6

https://github.com/IcterusGames/SimpleGrassTextured/assets/7874274/05c781cf-4cb0-4c6d-bdf0-1bda9c5475c1

If either of the videos is too difficult to view, please let me know if a google drive link is acceptable for you? I had to compress them for Github.
Thank you for your time.

**Comment by skison** [comment]
We're encountering the same issue with a test world that uses the Terrain3D terrain system for Godot 4.1.3.

**Comment by IcterusGames** [comment]
Try the new version 2.0.4 it should be fixed

**Comment by FeralBytes** [comment]
I can confirm that 2.0.4 does indeed fix the issue. Thank you very much for the rapid response. Question I see this was added:
```
const highp float EPSILON = 0.0001;
```
Not that our game is targeting mobile devices, but just curious will the high precision float still work on mobile devices?
